site_name: Knights of the Wombat

nav:
    - General: 
        - Home: index.md
    - Minecraft:
        - Home: mc/index.md
        - SkyFactory4:
            - General: mc/sf4/index.md
            - Real Filing Cabinet: mc/sf4/real-filing-cabinet.md
            - Weirding Gadget: mc/sf4/weirding-gadget.md

theme: 
    name: 'material'
    feature:
        tabs: true

plugins:
    - search

markdown_extensions:
  - toc:
        permalink: "#"
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_url: 'https://github.com/knightsofthewombat/gaming-resources'